/* auto-generated by NAPI-RS (header) + hand-maintained ActrError shim */
/* eslint-disable */

// ── ActrError ──────────────────────────────────────────────────────────────
//
// Every protocol-level failure is lifted to JS as an `ActrError` instance
// (subclass of `Error`) carrying structured classification metadata.
//
//   kind          fault-domain bucket — use for retry / DLQ policy.
//   code          exact variant name — use for fine-grained branching.
//   service_name  present only when `code === "DependencyNotFound"`.
//   retry_after_ms present when `code === "ConnectionNotReady"`.
//
// The raw native binding throws `Error` with a JSON payload in
// `error.message`; the `index.js` wrapper parses it and re-throws an
// `ActrError` so consumers see stable, typed metadata.

export type ActrErrorKind = 'Transient' | 'Client' | 'Internal' | 'Corrupt'

export type ActrErrorCode =
  | 'Unavailable'
  | 'ConnectionNotReady'
  | 'TimedOut'
  | 'NotFound'
  | 'PermissionDenied'
  | 'InvalidArgument'
  | 'UnknownRoute'
  | 'DependencyNotFound'
  | 'DecodeFailure'
  | 'NotImplemented'
  | 'Internal'
  | 'Config'
  | 'HyperBootstrap'

export declare class ActrError extends Error {
  readonly kind: ActrErrorKind
  readonly code: ActrErrorCode
  readonly service_name?: string
  readonly retry_after_ms?: number | null
  /** `true` iff `kind === 'Transient'` — retry with backoff. */
  isRetryable(): boolean
  /** `true` iff `code === 'ConnectionNotReady'`. */
  isConnectionNotReady(): boolean
  /** `true` iff `kind === 'Corrupt'` — route to Dead Letter Queue. */
  requiresDlq(): boolean
}

export declare class ActrNode {
  /** Create a client-only ActrNode directly from a config file path. */
  static fromFile(configPath: string): Promise<ActrNode>
  /**
   * Start the node and return ActrRef.
   *
   * One-shot: consumes the internal Hyper handle. A second call resolves
   * with `Node already started`.
   */
  start(): Promise<ActrRef>
}

export declare class ActrRef {
  /** Get the actor ID. */
  actorId(): ActrId
  /** Discover actors of the given type. */
  discover(targetType: ActrType, count: number): Promise<Array<ActrId>>
  /** Call remote actor (RPC). */
  call(target: ActrId, routeKey: string, payloadType: PayloadType, requestPayload: Buffer, timeoutMs: number): Promise<Buffer>
  /** Send one-way message (fire-and-forget). */
  tell(target: ActrId, routeKey: string, payloadType: PayloadType, messagePayload: Buffer): Promise<void>
  /** Trigger shutdown. */
  shutdown(): void
  /** Wait for shutdown to complete. */
  waitForShutdown(): Promise<void>
  /** Check if shutdown is in progress. */
  isShuttingDown(): boolean
}

export interface ActrId {
  realm: Realm
  serialNumber: number
  type: ActrType
}

export interface ActrType {
  manufacturer: string
  name: string
  version: string
}

export interface DataStream {
  streamId: string
  sequence: number
  payload: Buffer
  metadata: Array<MetadataEntry>
  timestampMs?: number
}

export interface MetadataEntry {
  key: string
  value: string
}

export declare const enum PayloadType {
  RpcReliable = 0,
  RpcSignal = 1,
  StreamReliable = 2,
  StreamLatencyFirst = 3,
  MediaRtp = 4
}

export interface Realm {
  realmId: number
}

export interface RpcEnvelopeBridge {
  routeKey: string
  payload: Buffer
  requestId: string
}

export interface StreamSignal {
  chunk: DataStream
  sender: ActrId
}
