// SPDX-License-Identifier: Apache-2.0

//! WIT -> wasm-bindgen ABI codegen for the browser path (Option U).
//!
//! Reads `core/framework/wit/actr-workload.wit` and emits three Rust
//! source files under `bindings/web/crates/actr-web-abi/src/`:
//!
//! - `types.rs` — every WIT record / enum / variant lowered to a serde-derived
//!   Rust struct or enum. `serde-wasm-bindgen`'s default shapes match
//!   what a hand-written JS host would produce / consume, so the two
//!   sides stay in sync without hand-crafted converters.
//! - `guest.rs` — every WIT host import lowered to a `#[wasm_bindgen]
//!   extern "C"` raw declaration plus a Rust `async` wrapper that
//!   marshals arguments/returns through `serde_wasm_bindgen` and awaits
//!   the `Promise` the JS host returns. Every wrapper returns a future
//!   even for WIT-sync imports, so user guest code can treat the whole
//!   surface uniformly.
//! - `host.rs` — every WIT guest export lowered to a
//!   `#[wasm_bindgen]`-exported entry point that unmarshals the JS
//!   payload, invokes a user trait, and serialises the result back. A
//!   `Workload` trait (async) is emitted alongside so consumers have a
//!   single thing to implement.
//!
//! The codegen is intentionally stringly-typed (`String` concatenation
//! with tiny helper fns) rather than `quote!` because the output is
//! dominated by `#[wasm_bindgen]` attributes and prose comments; those
//! read much better as raw text than as TokenStream incantations.

use std::collections::BTreeMap;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use anyhow::{Context, Result, anyhow, bail};
use heck::{ToPascalCase, ToSnakeCase};
use wit_parser::{Function, Resolve, Type, TypeDefKind, TypeId};

/// Canonical header prepended to every generated file. The timestamp is
/// deliberately omitted because reproducible output is what lets
/// `--check` compare bytes directly; the design doc recommendation for
/// a timestamp is superseded by that drift-gate constraint.
pub const HEADER: &str = "\
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/wit-compile-web — do not edit.
//
// Source: core/framework/wit/actr-workload.wit
// Regenerate with: cargo run -p actr-wit-compile-web
// Drift check:      cargo run -p actr-wit-compile-web -- --check
";

/// Output triple — the three Rust sources under `actr-web-abi/src/`.
#[derive(Debug, Clone)]
pub struct Generated {
    pub types: String,
    pub guest: String,
    pub host: String,
}

/// Default WIT input path relative to the repository root.
pub fn default_wit_path() -> PathBuf {
    PathBuf::from("core/framework/wit/actr-workload.wit")
}

/// Default output directory relative to the repository root.
pub fn default_out_dir() -> PathBuf {
    PathBuf::from("bindings/web/crates/actr-web-abi/src")
}

// ─────────────────────────────────────────────────────────────────────
// Model — a shallow, ordered projection of the WIT resolve that the
// emit functions walk. Keeping the walk separate from emission makes it
// cheap to re-emit a single file (used by the unit tests) and keeps the
// ordering deterministic.
// ─────────────────────────────────────────────────────────────────────

/// A record projected from WIT; kebab names are kept verbatim so the
/// emission helpers own the rename-to-Rust step.
#[derive(Debug, Clone)]
struct RecordDef {
    name: String,
    fields: Vec<(String, TypeRef)>,
}

/// A variant projected from WIT. `payload = None` means a unit case
/// (`shell`, `timed-out`, every case of `error-category`, ...).
#[derive(Debug, Clone)]
struct VariantDef {
    name: String,
    cases: Vec<(String, Option<TypeRef>)>,
}

/// An enum projected from WIT. Enum cases are always unit cases.
#[derive(Debug, Clone)]
struct EnumDef {
    name: String,
    cases: Vec<String>,
}

/// A function projected from a WIT interface.
#[derive(Debug, Clone)]
struct FuncDef {
    name: String,
    params: Vec<(String, TypeRef)>,
    /// `None` for unit return (`func() -> ()`).
    result: Option<TypeRef>,
}

/// Structural, stringly type reference — enough for the emitters to
/// produce the Rust form and decide the marshaling shape.
#[derive(Debug, Clone)]
enum TypeRef {
    Bool,
    U8,
    U16,
    U32,
    U64,
    S8,
    S16,
    S32,
    S64,
    F32,
    F64,
    Char,
    String_,
    Named(String),
    List(Box<TypeRef>),
    Option(Box<TypeRef>),
    Tuple(Vec<TypeRef>),
    Result_ {
        ok: Option<Box<TypeRef>>,
        err: Option<Box<TypeRef>>,
    },
}

impl TypeRef {
    /// Lower to Rust owned-value syntax (`Vec<u8>`, `Option<ActrId>`, ...).
    fn to_rust_owned(&self) -> String {
        match self {
            TypeRef::Bool => "bool".into(),
            TypeRef::U8 => "u8".into(),
            TypeRef::U16 => "u16".into(),
            TypeRef::U32 => "u32".into(),
            TypeRef::U64 => "u64".into(),
            TypeRef::S8 => "i8".into(),
            TypeRef::S16 => "i16".into(),
            TypeRef::S32 => "i32".into(),
            TypeRef::S64 => "i64".into(),
            TypeRef::F32 => "f32".into(),
            TypeRef::F64 => "f64".into(),
            TypeRef::Char => "char".into(),
            TypeRef::String_ => "String".into(),
            TypeRef::Named(n) => wit_type_name_to_rust(n),
            TypeRef::List(inner) => format!("Vec<{}>", inner.to_rust_owned()),
            TypeRef::Option(inner) => format!("Option<{}>", inner.to_rust_owned()),
            TypeRef::Tuple(items) => {
                let mut out = String::from("(");
                for (idx, item) in items.iter().enumerate() {
                    if idx > 0 {
                        out.push_str(", ");
                    }
                    out.push_str(&item.to_rust_owned());
                }
                if items.len() == 1 {
                    out.push(',');
                }
                out.push(')');
                out
            }
            TypeRef::Result_ { ok, err } => {
                let ok_s = ok
                    .as_ref()
                    .map(|t| t.to_rust_owned())
                    .unwrap_or_else(|| "()".into());
                let err_s = err
                    .as_ref()
                    .map(|t| t.to_rust_owned())
                    .unwrap_or_else(|| "()".into());
                format!("Result<{ok_s}, {err_s}>")
            }
        }
    }
}

#[derive(Debug, Clone, Default)]
struct WitModel {
    /// Ordered map (BTreeMap on WIT kebab name) so regeneration is
    /// byte-deterministic regardless of HashMap iteration order.
    records: BTreeMap<String, RecordDef>,
    enums: BTreeMap<String, EnumDef>,
    variants: BTreeMap<String, VariantDef>,
    host_imports: Vec<FuncDef>,
    guest_exports: Vec<FuncDef>,
}

/// Parse WIT from disk and flatten it into our walk-friendly model.
fn load_model(path: &Path) -> Result<WitModel> {
    let mut resolve = Resolve::new();
    resolve
        .push_file(path)
        .with_context(|| format!("failed to parse WIT at {}", path.display()))?;
    flatten(&resolve)
}

fn flatten(resolve: &Resolve) -> Result<WitModel> {
    let mut model = WitModel::default();

    // Gather named record/variant defs. wit-parser re-emits the same
    // name multiple times when `use types.{...}` aliases pull types
    // into `host` / `workload`; we dedupe by inserting on first sight.
    for (id, ty) in resolve.types.iter() {
        let Some(name) = ty.name.clone() else {
            continue;
        };
        match &ty.kind {
            TypeDefKind::Record(rec) => {
                let fields = rec
                    .fields
                    .iter()
                    .map(|f| (f.name.clone(), type_ref(resolve, &f.ty)))
                    .collect();
                model
                    .records
                    .entry(name.clone())
                    .or_insert(RecordDef { name, fields });
            }
            TypeDefKind::Variant(variant) => {
                let cases = variant
                    .cases
                    .iter()
                    .map(|c| {
                        let payload = c.ty.as_ref().map(|t| type_ref(resolve, t));
                        (c.name.clone(), payload)
                    })
                    .collect();
                model
                    .variants
                    .entry(name.clone())
                    .or_insert(VariantDef { name, cases });
            }
            TypeDefKind::Enum(enum_) => {
                let cases = enum_.cases.iter().map(|c| c.name.clone()).collect();
                model
                    .enums
                    .entry(name.clone())
                    .or_insert(EnumDef { name, cases });
            }
            TypeDefKind::Type(_) => {
                // Alias introduced by `use ...` re-export; skip.
                let _ = id;
            }
            TypeDefKind::Flags(_) | TypeDefKind::Resource => {
                bail!(
                    "type '{}' uses a kind (flags/resource) that Phase 0 didn't see \
                     — codegen needs to be extended before this lands",
                    name
                );
            }
            _ => {
                // Structural constructs (list/option/tuple/result) never
                // carry names and hit the anonymous branch above.
            }
        }
    }

    // Scoop functions from the two role-playing interfaces.
    for (_id, iface) in resolve.interfaces.iter() {
        let Some(iface_name) = iface.name.clone() else {
            continue;
        };
        match iface_name.as_str() {
            "host" => {
                for (fn_name, func) in &iface.functions {
                    model
                        .host_imports
                        .push(project_func(resolve, fn_name, func));
                }
            }
            "workload" => {
                for (fn_name, func) in &iface.functions {
                    model
                        .guest_exports
                        .push(project_func(resolve, fn_name, func));
                }
            }
            "types" => {
                // Types-only interface; no functions expected. Silently
                // ignore any the user may add (codegen would need to
                // decide their role explicitly anyway).
            }
            _ => {}
        }
    }

    // Sort functions by name so regeneration is deterministic — WIT
    // interface insertion order is implementation-defined in
    // wit-parser.
    model.host_imports.sort_by(|a, b| a.name.cmp(&b.name));
    model.guest_exports.sort_by(|a, b| a.name.cmp(&b.name));

    if model.records.is_empty()
        && model.enums.is_empty()
        && model.variants.is_empty()
        && model.host_imports.is_empty()
    {
        return Err(anyhow!(
            "WIT resolve produced no records/enums/variants/functions — parser likely misread the file"
        ));
    }
    Ok(model)
}

fn project_func(resolve: &Resolve, name: &str, func: &Function) -> FuncDef {
    let params = func
        .params
        .iter()
        .map(|p| (p.name.clone(), type_ref(resolve, &p.ty)))
        .collect();
    let result = func.result.as_ref().map(|t| type_ref(resolve, t));
    FuncDef {
        name: name.to_string(),
        params,
        result,
    }
}

fn type_ref(resolve: &Resolve, ty: &Type) -> TypeRef {
    match ty {
        Type::Bool => TypeRef::Bool,
        Type::U8 => TypeRef::U8,
        Type::U16 => TypeRef::U16,
        Type::U32 => TypeRef::U32,
        Type::U64 => TypeRef::U64,
        Type::S8 => TypeRef::S8,
        Type::S16 => TypeRef::S16,
        Type::S32 => TypeRef::S32,
        Type::S64 => TypeRef::S64,
        Type::F32 => TypeRef::F32,
        Type::F64 => TypeRef::F64,
        Type::Char => TypeRef::Char,
        Type::String => TypeRef::String_,
        Type::ErrorContext => TypeRef::Named("error-context".into()),
        Type::Id(id) => resolve_type_id(resolve, *id),
    }
}

fn resolve_type_id(resolve: &Resolve, id: TypeId) -> TypeRef {
    let def = &resolve.types[id];
    if let Some(name) = &def.name {
        return TypeRef::Named(name.clone());
    }
    match &def.kind {
        TypeDefKind::List(inner) => TypeRef::List(Box::new(type_ref(resolve, inner))),
        TypeDefKind::Option(inner) => TypeRef::Option(Box::new(type_ref(resolve, inner))),
        TypeDefKind::Tuple(t) => {
            TypeRef::Tuple(t.types.iter().map(|t| type_ref(resolve, t)).collect())
        }
        TypeDefKind::Result(r) => TypeRef::Result_ {
            ok: r.ok.as_ref().map(|t| Box::new(type_ref(resolve, t))),
            err: r.err.as_ref().map(|t| Box::new(type_ref(resolve, t))),
        },
        TypeDefKind::Type(inner) => type_ref(resolve, inner),
        other => TypeRef::Named(format!("<unsupported:{}>", other.as_str())),
    }
}

// ─────────────────────────────────────────────────────────────────────
// Naming helpers
// ─────────────────────────────────────────────────────────────────────

/// `actr-id` -> `ActrId`, `error-category` -> `ErrorCategory`, ...
fn wit_type_name_to_rust(name: &str) -> String {
    name.to_pascal_case()
}

/// WIT field / parameter name -> Rust identifier. Strips any leading
/// `%` the parser may have left behind (keyword escapes — `actr-id`'s
/// `%type` is the live example), snake-cases the rest, and rewrites
/// Rust reserved words to safe aliases.
fn wit_ident_to_rust(name: &str) -> String {
    let stripped = name.strip_prefix('%').unwrap_or(name);
    let snaked = stripped.to_snake_case();
    match snaked.as_str() {
        // `type` is the one that actually shows up today (`actr-id.type`).
        // Renaming to `actr_type` is clearer than `r#type` because it
        // preserves the surrounding context (`actor-id` record). The
        // other entries are prophylactic — WIT reserves no keywords the
        // way Rust does, so any future contract drift could hit them.
        "type" => "actr_type".into(),
        "crate" | "fn" | "self" | "super" | "mod" | "pub" | "ref" | "use" | "where" | "match"
        | "move" | "impl" | "trait" | "let" | "box" | "const" | "static" | "unsafe" | "async"
        | "await" | "dyn" | "as" | "in" | "for" | "loop" | "while" | "if" | "else" | "return"
        | "break" | "continue" | "struct" | "enum" | "union" | "extern" | "false" | "true" => {
            format!("r#{snaked}")
        }
        _ => snaked,
    }
}

/// WIT variant case name -> Rust enum variant (PascalCase, with the
/// same keyword-escape rule as field names for safety).
fn wit_case_to_rust(name: &str) -> String {
    name.to_pascal_case()
}

/// WIT function name -> Rust snake_case fn name.
fn wit_fn_to_rust(name: &str) -> String {
    wit_ident_to_rust(name)
}

/// JS-side import name convention: `host.call-raw` surfaces as
/// `actrHostCallRaw` so hand-written JS glue can expose them on a
/// single namespace object without collisions.
fn js_host_import_name(wit_fn: &str) -> String {
    format!("actrHost{}", wit_fn.to_pascal_case())
}

/// JS-side export name for a workload hook.
fn js_workload_export_name(wit_fn: &str) -> String {
    // snake-case mirrors the WIT shape 1:1 (kebab -> snake); this is
    // what guest JS consumers expect when they call through
    // `instance.exports.on_start()` etc.
    wit_fn.replace('-', "_")
}

// ─────────────────────────────────────────────────────────────────────
// Emit — types.rs
// ─────────────────────────────────────────────────────────────────────

fn emit_types(model: &WitModel) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push('\n');
    out.push_str(
        "//! Serde-derived record / enum / variant definitions lowered from \n\
         //! `core/framework/wit/actr-workload.wit`.\n\
         //!\n\
         //! Every type derives `Serialize` + `Deserialize` so \n\
         //! `serde-wasm-bindgen` can carry them across the Rust <-> JS\n\
         //! boundary without a hand-written converter. Field names are\n\
         //! snake-cased Rust idents; `#[serde(rename)]` keeps the wire\n\
         //! shape WIT-exact (kebab / escaped-keyword tokens included).\n",
    );
    out.push_str("#![allow(non_snake_case)]\n");
    out.push_str("#![allow(clippy::large_enum_variant)]\n\n");
    out.push_str("use serde::{Deserialize, Serialize};\n\n");

    // Records first (alphabetised via BTreeMap iteration).
    for rec in model.records.values() {
        emit_record(&mut out, rec);
        out.push('\n');
    }

    // Enums.
    for enum_ in model.enums.values() {
        emit_enum(&mut out, enum_);
        out.push('\n');
    }

    // Variants.
    for var in model.variants.values() {
        emit_variant(&mut out, var);
        out.push('\n');
    }

    out
}

fn emit_record(out: &mut String, rec: &RecordDef) {
    let struct_name = wit_type_name_to_rust(&rec.name);
    out.push_str(&format!("/// Lowered from WIT `record {}`.\n", rec.name));
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {struct_name} {{\n"));
    for (field_name, field_ty) in &rec.fields {
        let rust_field = wit_ident_to_rust(field_name);
        let rust_ty = field_ty.to_rust_owned();
        // Preserve the exact WIT wire name so serde-wasm-bindgen
        // produces/consumes a JS object shape a hand-written JS host
        // would write (kebab-case / `%type` stays as `type`).
        let wire_name = field_name.strip_prefix('%').unwrap_or(field_name);
        if wire_name != rust_field {
            out.push_str(&format!("    #[serde(rename = \"{wire_name}\")]\n"));
        }
        out.push_str(&format!("    pub {rust_field}: {rust_ty},\n"));
    }
    out.push_str("}\n");
}

fn emit_enum(out: &mut String, enum_: &EnumDef) {
    let enum_name = wit_type_name_to_rust(&enum_.name);
    out.push_str(&format!("/// Lowered from WIT `enum {}`.\n", enum_.name));
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub enum {enum_name} {{\n"));
    for case_name in &enum_.cases {
        let rust_case = wit_case_to_rust(case_name);
        if rust_case != *case_name {
            out.push_str(&format!("    #[serde(rename = \"{case_name}\")]\n"));
        }
        out.push_str(&format!("    {rust_case},\n"));
    }
    out.push_str("}\n");
}

fn emit_variant(out: &mut String, var: &VariantDef) {
    let enum_name = wit_type_name_to_rust(&var.name);
    out.push_str(&format!("/// Lowered from WIT `variant {}`.\n", var.name));
    // Externally-tagged is serde's default. For the all-unit `error-
    // category` this yields `{"handler-panic": null}` which matches
    // what `serde-wasm-bindgen` on the host emits from the same enum
    // definition, so both sides stay symmetric without extra attrs.
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub enum {enum_name} {{\n"));
    for (case_name, payload) in &var.cases {
        let rust_case = wit_case_to_rust(case_name);
        // Only emit the rename when the Pascal form differs from the
        // WIT kebab form — keeps the diff noise low and the wire shape
        // identical to WIT.
        if rust_case != *case_name {
            out.push_str(&format!("    #[serde(rename = \"{case_name}\")]\n"));
        }
        match payload {
            Some(ty) => {
                out.push_str(&format!("    {rust_case}({}),\n", ty.to_rust_owned()));
            }
            None => {
                out.push_str(&format!("    {rust_case},\n"));
            }
        }
    }
    out.push_str("}\n");
}

// ─────────────────────────────────────────────────────────────────────
// Emit — guest.rs
// ─────────────────────────────────────────────────────────────────────
//
// For every host import we emit three things:
//  1. A raw `#[wasm_bindgen(js_name = "actrHost<Name>", catch)]` extern
//     declaration. The returned `Promise` is typed through `JsValue`
//     so the Rust wrapper can `.await` regardless of whether the JS
//     side hands back a `Promise.resolve(value)` or a real async
//     function. `catch` converts thrown errors into `Err(JsValue)`
//     rather than panicking the wasm module.
//  2. A typed Rust `async fn` that serialises the inputs, awaits the
//     promise, and deserialises the output.
//  3. One shared `serde_err` / `js_err` helper at the top so every
//     wrapper body stays short.

fn emit_guest(model: &WitModel) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push('\n');
    out.push_str(
        "//! Guest-side wrappers around `interface host` imports.\n\
         //!\n\
         //! Each WIT host function appears here twice: once as a raw\n\
         //! `#[wasm_bindgen] extern \"C\"` declaration that resolves\n\
         //! against the JS `actrHost*` namespace the DOM bridge\n\
         //! exposes, and once as a typed Rust `async fn` that handles\n\
         //! serde marshaling and promise awaiting.\n\
         //!\n\
         //! Every wrapper is `async` — even for imports that look\n\
         //! sync in WIT — because the JS host is free to implement\n\
         //! any of them as a Promise-returning function, and making\n\
         //! callers uniformly write `.await` keeps the surface\n\
         //! predictable.\n",
    );
    out.push_str("#![allow(clippy::useless_conversion)]\n");
    out.push_str("#![allow(clippy::unused_unit)]\n\n");
    out.push_str("use wasm_bindgen::prelude::*;\n");
    out.push_str("use wasm_bindgen_futures::JsFuture;\n\n");
    out.push_str("use crate::types::*;\n\n");

    // Unified error translation helpers. Both serde and wasm-bindgen
    // errors have to collapse to a single `JsValue` so the wrappers
    // can return `Result<_, JsValue>` uniformly.
    out.push_str(
        r#"/// Convert a serde-wasm-bindgen marshaling error into a `JsValue`
/// so wrapper signatures stay uniform.
#[inline]
fn serde_err(e: serde_wasm_bindgen::Error) -> JsValue {
    JsValue::from(e)
}

"#,
    );

    // Raw extern block. Every import is declared as returning a
    // `js_sys::Promise` so awaiting is trivial; for genuinely sync
    // imports the JS side can always use `Promise.resolve(x)`.
    //
    // `js_name = actrHost<PascalName>` keeps the JS shape flat: the
    // DOM bridge exposes one top-level function per import, which
    // composes more cleanly with ES-module exports than a namespaced
    // object would.
    //
    // Every declaration takes `request_id: JsValue` as the first
    // parameter so the SW-host side can route the call back to the
    // correct per-dispatch `RuntimeContext` (see Phase 6 γ-unified
    // design §3.4 / §3.6). This fixes the TD-003 concurrency hazard
    // where a single thread-local context was shared across dispatches.
    out.push_str("#[wasm_bindgen]\n");
    out.push_str("extern \"C\" {\n");
    for func in &model.host_imports {
        let js_name = js_host_import_name(&func.name);
        let raw_name = format!("__actr_host_{}", wit_fn_to_rust(&func.name));
        out.push_str(&format!(
            "    #[wasm_bindgen(catch, js_name = \"{js_name}\")]\n"
        ));
        out.push_str(&format!("    fn {raw_name}(request_id: JsValue"));
        for (pname, _pty) in func.params.iter() {
            let rust_pname = wit_ident_to_rust(pname);
            out.push_str(&format!(", {rust_pname}: JsValue"));
        }
        out.push_str(") -> Result<js_sys::Promise, JsValue>;\n");
    }
    out.push_str("}\n\n");

    // Typed wrappers.
    for func in &model.host_imports {
        emit_host_import_wrapper(&mut out, func);
        out.push('\n');
    }

    out
}

fn emit_host_import_wrapper(out: &mut String, func: &FuncDef) {
    let rust_fn = wit_fn_to_rust(&func.name);
    let wrapper_fn = format!("{rust_fn}_with_request_id");
    let raw_name = format!("__actr_host_{rust_fn}");

    out.push_str(&format!(
        "/// Guest-side wrapper for WIT `host.{}`.\n",
        func.name
    ));
    out.push_str(
        "///\n\
         /// The `request_id` first parameter threads per-dispatch context\n\
         /// through to the SW host (Phase 6 γ-unified §3.4). Callers are\n\
         /// expected to pass `Context::request_id()`; manual construction\n\
         /// is discouraged.\n",
    );

    // Parameter list on the Rust surface. Scalars pass by value; heap
    // and named types pass by reference so the caller doesn't give up
    // ownership to a function that is only going to serialise it.
    //
    // `request_id: &str` leads the list so the signature mirrors the
    // SW-host `host_*_async` exports on the other side of the bridge.
    out.push_str(&format!("pub async fn {wrapper_fn}(request_id: &str"));
    let mut arg_surface: Vec<(String, String)> = Vec::new();
    for (pname, pty) in func.params.iter() {
        let rust_pname = wit_ident_to_rust(pname);
        let (rust_ty, is_ref) = rust_param_type(pty);
        arg_surface.push((rust_pname.clone(), rust_ty.clone()));
        out.push_str(&format!(", {rust_pname}: {rust_ty}"));
        let _ = is_ref; // kept for readability; unused directly
    }
    out.push_str(") -> ");
    out.push_str(&wrapper_return_type(func.result.as_ref()));
    out.push_str(" {\n");

    // Serialise the request_id (as a plain JS string) and then each
    // typed argument into its own `JsValue`.
    out.push_str("    let __js_request_id = JsValue::from_str(request_id);\n");
    for (idx, (pname, _pty)) in func.params.iter().enumerate() {
        let rust_pname = wit_ident_to_rust(pname);
        let var = format!("__js_arg{idx}");
        out.push_str(&format!(
            "    let {var} = serde_wasm_bindgen::to_value(&{rust_pname}).map_err(serde_err)?;\n"
        ));
        let _ = var;
    }

    // Call the raw import — request_id first, then the WIT-typed args.
    out.push_str(&format!(
        "    let __js_promise = {raw_name}(__js_request_id"
    ));
    for idx in 0..func.params.len() {
        out.push_str(&format!(", __js_arg{idx}"));
    }
    out.push_str(")?;\n");

    // Await the Promise and deserialise the result according to the
    // WIT return shape. Unit return (`func() -> ()`) short-circuits
    // the deserialise step.
    out.push_str("    let __js_result = JsFuture::from(__js_promise).await?;\n");
    match &func.result {
        None => {
            out.push_str("    let _ = __js_result;\n");
            out.push_str("    Ok(())\n");
        }
        Some(_) => {
            out.push_str(
                "    let __out = serde_wasm_bindgen::from_value(__js_result).map_err(serde_err)?;\n",
            );
            out.push_str("    Ok(__out)\n");
        }
    }

    out.push_str("}\n");

    let _ = arg_surface;
}

/// Return type of a guest-side wrapper: always `Result<_, JsValue>`
/// so raw JS exceptions and serde errors collapse to one channel.
/// The inner Ok arm mirrors the WIT return, with unit lifted to `()`.
fn wrapper_return_type(result: Option<&TypeRef>) -> String {
    let ok = result
        .map(|t| t.to_rust_owned())
        .unwrap_or_else(|| "()".into());
    format!("Result<{ok}, JsValue>")
}

/// Decide Rust parameter surface for a typed wrapper.
///
/// Scalars take by value (they are Copy). String / Vec / named types
/// take by owned value as well — the wrapper immediately serialises
/// through serde, so forcing a `&T` would only add a reborrow step
/// with no ownership benefit.
fn rust_param_type(ty: &TypeRef) -> (String, bool) {
    // `true` here signaled reference-passing in an earlier revision;
    // kept in the return shape so the emit fn can switch later without
    // refactoring the call site.
    (ty.to_rust_owned(), false)
}

// ─────────────────────────────────────────────────────────────────────
// Emit — host.rs
// ─────────────────────────────────────────────────────────────────────
//
// A guest export surfaces on two layers:
//  - A Rust `trait Workload` the user workload implements (infallible
//    or `Result<_, ActrError>` matches the WIT result shape exactly).
//  - A set of free `#[wasm_bindgen]` fns that the JS host calls. Each
//    entry point deserialises params, calls into a user-installed
//    boxed `dyn Workload`, and serialises the result back.
//
// The boxed handler lives in a `OnceCell`-ish slot behind a setter
// (`set_workload`). This matches what the browser runtime actually
// needs: one workload instance per wasm module, initialised during
// the module bootstrap. Multiple-handler support isn't in scope for
// the ABI and belongs in a higher layer anyway.

fn emit_host(model: &WitModel) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push('\n');
    out.push_str(
        "//! Host-side wrappers around `interface workload` exports.\n\
         //!\n\
         //! Emits an internal `Workload` trait and a set of\n\
         //! `#[wasm_bindgen]` free functions the browser host\n\
         //! (service worker / DOM bridge) calls. Each entry point\n\
         //! deserialises JS arguments, dispatches to the registered\n\
         //! workload instance, and serialises the response back.\n\
         //!\n\
         //! The `Workload` trait is `#[doc(hidden)] pub` — the\n\
         //! public entry point is [`register_workload`], which the\n\
         //! `actr_framework::entry!` macro (Phase 6b) expands to. User\n\
         //! code never implements this trait directly; the framework\n\
         //! glues a WIT-generated dispatcher onto the user's\n\
         //! domain-specific workload and hands *that* to\n\
         //! `register_workload`.\n\
         //!\n\
         //! Registration is single-shot — the wasm bootstrap installs\n\
         //! one boxed handler, and every export call resolves against\n\
         //! it. Attempting to dispatch before registration traps with\n\
         //! an explicit JsError.\n",
    );
    out.push_str("#![allow(clippy::unused_unit)]\n\n");
    out.push_str("use std::cell::RefCell;\n\n");
    out.push_str("use async_trait::async_trait;\n");
    out.push_str("use wasm_bindgen::prelude::*;\n\n");
    out.push_str("use crate::types::*;\n\n");

    // Trait definition — crate-private. External callers use
    // `register_workload` plus the framework-generated dispatcher.
    out.push_str(
        "/// Internal workload adapter trait. Not for direct\n\
         /// implementation by user code — use\n\
         /// `actr_framework::entry!` which expands into a blanket impl\n\
         /// that routes into the user's typed handlers.\n\
         ///\n\
         /// Marked `#[doc(hidden)] pub` rather than `pub(crate)` so it\n\
         /// can appear as a bound on the public [`register_workload`]\n\
         /// function without triggering `private_bounds`. Users must\n\
         /// still not implement it manually — the `actr_framework::entry!`\n\
         /// macro is the only sanctioned impl path.\n\
         ///\n\
         /// Method shapes mirror the WIT `workload` interface exactly,\n\
         /// including which hooks are fallible (the four lifecycle\n\
         /// hooks return `Result<_, ActrError>`) and which are\n\
         /// infallible (all the observation hooks).\n",
    );
    out.push_str("#[async_trait(?Send)]\n");
    out.push_str("#[doc(hidden)]\n");
    out.push_str("pub trait Workload: 'static {\n");
    for func in &model.guest_exports {
        emit_trait_method_signature(&mut out, func);
        out.push_str(";\n");
    }
    out.push_str("}\n\n");

    // Handler slot + registration. The wasm-bindgen browser target is
    // strictly single-threaded, so `thread_local!` + `RefCell` is
    // sound here: every export entry point runs on the same worker /
    // main thread the `register_workload` call ran on. Using a
    // `static OnceLock` would force the trait object to be
    // `Send + Sync`, which is both false for many user workloads and
    // a false promise (browsers cannot schedule it across threads
    // anyway).
    //
    // The `Box<dyn Workload>` is leaked into a `&'static dyn Workload`
    // inside `workload()` so awaited method calls can outlive the
    // `RefCell` borrow. This is safe because registration is
    // single-shot and the handler lives until process shutdown.
    out.push_str(
        r#"thread_local! {
    static WORKLOAD: RefCell<Option<&'static dyn Workload>> = const { RefCell::new(None) };
}

/// Install the workload implementation for this wasm module. Called
/// exactly once during the module's bootstrap — typically from the
/// `#[wasm_bindgen(start)]` glue that `actr_framework::entry!`
/// expands to.
///
/// The installed handler is intentionally leaked to `'static`: the
/// browser path registers exactly one workload during bootstrap and
/// keeps it alive for the lifetime of the wasm instance. Passing a
/// `Clone` bound anticipates the P6-I integration where a cloned
/// handle may be handed to each per-dispatch `WebContext`.
///
/// Panics if called more than once — double-registration is always a
/// programming error (one wasm module = one workload).
pub fn register_workload<W: Workload + Clone + 'static>(w: W) {
    WORKLOAD.with(|slot| {
        let mut slot = slot.borrow_mut();
        if slot.is_some() {
            panic!("actr-web-abi: workload already registered");
        }
        let leaked: &'static dyn Workload = Box::leak(Box::new(w));
        *slot = Some(leaked);
    });
}

#[inline]
fn workload() -> Result<&'static dyn Workload, JsValue> {
    WORKLOAD
        .with(|slot| slot.borrow().as_ref().copied())
        .ok_or_else(|| JsValue::from_str("actr-web-abi: workload not registered"))
}

#[inline]
fn serde_err(e: serde_wasm_bindgen::Error) -> JsValue {
    JsValue::from(e)
}

"#,
    );

    // Export entry points.
    for func in &model.guest_exports {
        emit_workload_export(&mut out, func);
        out.push('\n');
    }

    out
}

fn emit_trait_method_signature(out: &mut String, func: &FuncDef) {
    let rust_fn = wit_fn_to_rust(&func.name);
    out.push_str(&format!("    async fn {rust_fn}(&self"));
    for (pname, pty) in &func.params {
        let rust_pname = wit_ident_to_rust(pname);
        let rust_ty = pty.to_rust_owned();
        out.push_str(&format!(", {rust_pname}: {rust_ty}"));
    }
    out.push(')');
    // Return shape. WIT `func() -> ()` -> Rust `()`. WIT
    // `result<T, actr-error>` -> `Result<T, ActrError>` with unit
    // lifted where needed.
    match &func.result {
        None => {}
        Some(ty) => {
            out.push_str(&format!(" -> {}", ty.to_rust_owned()));
        }
    }
}

fn emit_workload_export(out: &mut String, func: &FuncDef) {
    let rust_fn = wit_fn_to_rust(&func.name);
    let js_name = js_workload_export_name(&func.name);

    out.push_str(&format!(
        "/// Host-exported entry for WIT `workload.{}`.\n",
        func.name
    ));
    out.push_str(&format!("#[wasm_bindgen(js_name = \"{js_name}\")]\n"));
    out.push_str(&format!("pub async fn __actr_workload_{rust_fn}("));

    // Params come in as JsValue; we deserialise inside the body so
    // the export's Rust surface stays trivially wasm-bindgen-typable.
    for (idx, (pname, _pty)) in func.params.iter().enumerate() {
        if idx > 0 {
            out.push_str(", ");
        }
        let rust_pname = wit_ident_to_rust(pname);
        out.push_str(&format!("{rust_pname}: JsValue"));
    }
    out.push_str(") -> Result<JsValue, JsValue> {\n");

    out.push_str("    let __w = workload()?;\n");

    // Deserialise each param into its typed Rust value.
    let mut call_args: Vec<String> = Vec::with_capacity(func.params.len());
    for (pname, pty) in &func.params {
        let rust_pname = wit_ident_to_rust(pname);
        let rust_ty = pty.to_rust_owned();
        let var = format!("__p_{rust_pname}");
        out.push_str(&format!(
            "    let {var}: {rust_ty} = serde_wasm_bindgen::from_value({rust_pname}).map_err(serde_err)?;\n"
        ));
        call_args.push(var);
    }

    // Invoke the trait method.
    match &func.result {
        None => {
            out.push_str(&format!("    __w.{rust_fn}("));
            for (idx, arg) in call_args.iter().enumerate() {
                if idx > 0 {
                    out.push_str(", ");
                }
                out.push_str(arg);
            }
            out.push_str(").await;\n");
            out.push_str("    Ok(JsValue::UNDEFINED)\n");
        }
        Some(_) => {
            out.push_str(&format!("    let __r = __w.{rust_fn}("));
            for (idx, arg) in call_args.iter().enumerate() {
                if idx > 0 {
                    out.push_str(", ");
                }
                out.push_str(arg);
            }
            out.push_str(").await;\n");
            out.push_str("    serde_wasm_bindgen::to_value(&__r).map_err(serde_err)\n");
        }
    }

    out.push_str("}\n");
}

// ─────────────────────────────────────────────────────────────────────
// Public entry point + --check drift detection
// ─────────────────────────────────────────────────────────────────────

/// Generate all three Rust sources from a WIT file on disk. Used by
/// both the binary's write path and the `--check` path so the bytes
/// being diffed are the exact bytes the write path would produce.
pub fn generate_from_path(wit_path: &Path) -> Result<Generated> {
    let model = load_model(wit_path)?;
    Ok(Generated {
        types: format_rust_source("types.rs", emit_types(&model))?,
        guest: format_rust_source("guest.rs", emit_guest(&model))?,
        host: format_rust_source("host.rs", emit_host(&model))?,
    })
}

fn format_rust_source(file: &'static str, source: String) -> Result<String> {
    let mut child = Command::new("rustfmt")
        .args(["--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .with_context(|| "spawn rustfmt for generated source")?;

    child
        .stdin
        .as_mut()
        .expect("rustfmt stdin is piped")
        .write_all(source.as_bytes())
        .with_context(|| format!("write generated {file} to rustfmt"))?;

    let output = child
        .wait_with_output()
        .with_context(|| format!("wait for rustfmt on generated {file}"))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!("rustfmt failed for generated {file}: {stderr}");
    }

    String::from_utf8(output.stdout)
        .with_context(|| format!("rustfmt output for {file} was not UTF-8"))
}

/// Write the three sources under `out_dir`, creating the directory if
/// it doesn't exist.
pub fn write_outputs(out_dir: &Path, out_gen: &Generated) -> Result<()> {
    std::fs::create_dir_all(out_dir).with_context(|| format!("create {}", out_dir.display()))?;
    std::fs::write(out_dir.join("types.rs"), &out_gen.types)
        .with_context(|| format!("write {}/types.rs", out_dir.display()))?;
    std::fs::write(out_dir.join("guest.rs"), &out_gen.guest)
        .with_context(|| format!("write {}/guest.rs", out_dir.display()))?;
    std::fs::write(out_dir.join("host.rs"), &out_gen.host)
        .with_context(|| format!("write {}/host.rs", out_dir.display()))?;
    Ok(())
}

/// Drift report produced by [`check_outputs`]. An empty `diffs` vec
/// means the checked-in sources are up to date.
#[derive(Debug, Default)]
pub struct CheckReport {
    pub diffs: Vec<DriftEntry>,
}

#[derive(Debug)]
pub struct DriftEntry {
    pub file: &'static str,
    pub reason: &'static str,
}

/// Compare the generated output to the on-disk sources without
/// writing. Returns a [`CheckReport`]; an empty `diffs` vec means the
/// caller can exit 0.
pub fn check_outputs(out_dir: &Path, out_gen: &Generated) -> Result<CheckReport> {
    let mut report = CheckReport::default();
    for (file, expected) in [
        ("types.rs", &out_gen.types),
        ("guest.rs", &out_gen.guest),
        ("host.rs", &out_gen.host),
    ] {
        let path = out_dir.join(file);
        let on_disk = match std::fs::read_to_string(&path) {
            Ok(s) => s,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                report.diffs.push(DriftEntry {
                    file: static_str(file),
                    reason: "missing on disk",
                });
                continue;
            }
            Err(e) => return Err(anyhow!("read {}: {e}", path.display())),
        };
        if on_disk != *expected {
            report.diffs.push(DriftEntry {
                file: static_str(file),
                reason: "content differs from generator output",
            });
        }
    }
    Ok(report)
}

/// Interns a `&str` to `&'static str` by matching the three known
/// filenames. Keeps [`DriftEntry`] owning `'static` borrows for cheap
/// formatting without dragging in a `'static` string dep.
fn static_str(s: &str) -> &'static str {
    match s {
        "types.rs" => "types.rs",
        "guest.rs" => "guest.rs",
        "host.rs" => "host.rs",
        other => Box::leak(other.to_string().into_boxed_str()),
    }
}

// ─────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    const MINI_WIT: &str = r#"
        package test:mini@0.1.0;

        interface types {
            record sample {
                field-a: string,
                count: u32,
                %type: actr-type,
            }

            record actr-type {
                name: string,
            }

            variant colour {
                red,
                green(string),
            }

            enum delivery-state {
                not-sent,
                delivery-uncertain,
            }
        }

        interface host {
            use types.{sample, actr-type};
            ping: func(arg: sample) -> result<u32, string>;
            log-message: func(msg: string);
        }

        interface workload {
            use types.{sample};
            dispatch: func(arg: sample) -> result<u32, string>;
            on-start: func();
        }

        world w {
            import host;
            export workload;
        }
    "#;

    fn load_inmem(source: &str) -> WitModel {
        let mut resolve = Resolve::new();
        resolve.push_str("in-memory.wit", source).expect("parse");
        flatten(&resolve).expect("flatten")
    }

    #[test]
    fn records_and_variants_surface() {
        let model = load_inmem(MINI_WIT);
        assert!(model.records.contains_key("sample"));
        assert!(model.enums.contains_key("delivery-state"));
        assert!(model.variants.contains_key("colour"));
    }

    #[test]
    fn types_rs_contains_escaped_keyword_rename() {
        let model = load_inmem(MINI_WIT);
        let out = emit_types(&model);
        // The WIT field `%type` on `sample` should become
        // `actr_type` in Rust, with a serde rename back to the WIT
        // wire form (`type`, no leading %).
        assert!(
            out.contains("pub actr_type: ActrType"),
            "output was:\n{out}"
        );
        assert!(out.contains("#[serde(rename = \"type\")]"));
    }

    #[test]
    fn guest_rs_has_async_wrappers() {
        let model = load_inmem(MINI_WIT);
        let out = emit_guest(&model);
        assert!(out.contains("pub async fn ping_with_request_id"));
        assert!(out.contains("pub async fn log_message_with_request_id"));
        assert!(out.contains("JsFuture::from"));
    }

    #[test]
    fn guest_rs_threads_request_id_through() {
        let model = load_inmem(MINI_WIT);
        let out = emit_guest(&model);
        // Wrapper takes `request_id: &str` as the leading parameter.
        assert!(
            out.contains("pub async fn ping_with_request_id(request_id: &str"),
            "output was:\n{out}"
        );
        // Extern declaration takes `request_id: JsValue` first so the
        // SW host can dispatch by request_id.
        assert!(
            out.contains("fn __actr_host_ping(request_id: JsValue"),
            "output was:\n{out}"
        );
        // Body converts it to a JsString before the raw call.
        assert!(out.contains("JsValue::from_str(request_id)"));
        // Call threads the request_id JS value as the first argument.
        assert!(out.contains("__actr_host_ping(__js_request_id"));
    }

    #[test]
    fn host_rs_has_crate_private_trait_and_register() {
        let model = load_inmem(MINI_WIT);
        let out = emit_host(&model);
        // Trait is `#[doc(hidden)] pub` so it can bound the public
        // `register_workload` fn without triggering `private_bounds`.
        assert!(out.contains("#[doc(hidden)]\npub trait Workload"));
        assert!(
            !out.contains("pub(crate) trait Workload"),
            "Workload trait should no longer be pub(crate)"
        );
        assert!(out.contains("pub fn register_workload"));
        assert!(out.contains("W: Workload + Clone + 'static"));
        assert!(out.contains("async fn dispatch"));
        assert!(out.contains("async fn on_start"));
        assert!(out.contains("#[wasm_bindgen(js_name = \"dispatch\")"));
    }
}
